// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tasinmaz.Data;

#nullable disable

namespace tasinmaz.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tasinmaz.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kullaniciad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kullanicisoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("tasinmaz.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Loglar");
                });

            modelBuilder.Entity("tasinmaz.Models.Tasinmaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ada")
                        .HasColumnType("integer");

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("il")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ilce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("kullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("mahalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nitelik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("parsel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("kullaniciId");

                    b.ToTable("Tasinmazlar");
                });

            modelBuilder.Entity("tasinmaz.Models.Tasinmaz", b =>
                {
                    b.HasOne("tasinmaz.Models.Kullanici", "kullanici")
                        .WithMany("Tasinmazz")
                        .HasForeignKey("kullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("tasinmaz.Models.Kullanici", b =>
                {
                    b.Navigation("Tasinmazz");
                });
#pragma warning restore 612, 618
        }
    }
}
